/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.compa.mvdb_desktop;

import com.alibaba.fastjson.JSONObject;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ElKebabHenry
 */
public final class ViewMovie extends javax.swing.JFrame {

    private int movieId;

    /**
     * Creates new form ViewMovie
     * @param movieId, the movie viewed at the moment
     * @throws java.io.IOException
     */
    public ViewMovie(int movieId) throws IOException {
        this.movieId = movieId;
        initComponents();
        fetchMovie(movieId);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        runtime = new javax.swing.JLabel();
        genre = new javax.swing.JLabel();
        plot = new javax.swing.JLabel();
        imdbScore = new javax.swing.JLabel();
        ageRated = new javax.swing.JLabel();
        possessor = new javax.swing.JLabel();
        Delete = new javax.swing.JButton();
        edit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        title.setText("title");

        runtime.setText("runtime");

        genre.setText("genre");

        plot.setText("plot");

        imdbScore.setText("imdbScore");

        ageRated.setText("ageRated");

        possessor.setText("possessor");

        Delete.setText("DELETE");
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
        });

        edit.setText("EDIT");
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(plot))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(possessor)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(runtime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ageRated))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(edit)
                        .addGap(108, 108, 108)))
                .addGap(132, 132, 132))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(genre, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(149, 149, 149)
                        .addComponent(imdbScore)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Delete)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(ageRated)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genre)
                            .addComponent(imdbScore))
                        .addGap(30, 30, 30)
                        .addComponent(runtime)
                        .addGap(36, 36, 36)
                        .addComponent(plot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(possessor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Delete)
                            .addComponent(edit))
                        .addGap(18, 18, 18))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        try {
            this.DeleteMovie(this.movieId);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_DeleteMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        try {
            new EditFilm(movieId).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(ViewMovie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editMouseClicked

    public void DeleteMovie(int id) throws IOException {
        JSONObject delete = BackendRequest.getInstance().request("/movie/" + id, BackendRequest.CallMethod.DELETE);
    }

    public void fetchMovie(int id) throws IOException {

        try {
            JSONObject res = BackendRequest.getInstance().request("/movie/" + id, BackendRequest.CallMethod.GET, null);
            System.out.println("Hello");

            this.title.setText("Title: " + res.getString("title"));
            this.plot.setText("Plot: " + res.getString("plot"));
            this.runtime.setText("Runtime: " + res.getString("runtime"));
            this.ageRated.setText("Age Rate: " + res.getString("age_rated"));
            this.genre.setText("Genres: " + res.getString("genre"));
            this.imdbScore.setText("Score on Imdb: " + res.getString("imdb_score"));
            this.possessor.setText("Possessor of movie: " + res.getString("possessor"));

        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(ViewMovie.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JLabel ageRated;
    private javax.swing.JButton edit;
    private javax.swing.JLabel genre;
    private javax.swing.JLabel imdbScore;
    private javax.swing.JLabel plot;
    private javax.swing.JLabel possessor;
    private javax.swing.JLabel runtime;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
